import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'

const GENERATED_DIR = join(import.meta.dir, '..', 'server', 'generated')
const SCHEMA_FILE = join(GENERATED_DIR, 'herdr-schema.json')
const PROTOCOL_FILE = join(GENERATED_DIR, 'protocol.ts')

export interface ISchemaMetadata {
  protocol: number
  schema_version: number
  title?: string
}

export const fetchInstalledSchema = async (): Promise<{ rawJson: string; parsed: any }> => {
  const proc = Bun.spawn(['herdr', 'api', 'schema', '--json'], {
    stdout: 'pipe',
    stderr: 'pipe'
  })

  const [stdoutBytes, stderrBytes] = await Promise.all([
    new Response(proc.stdout).arrayBuffer(),
    new Response(proc.stderr).arrayBuffer()
  ])

  const exitCode = await proc.exited
  if (exitCode !== 0) {
    const errText = new TextDecoder().decode(stderrBytes).trim()
    throw new Error(`"herdr api schema --json" failed with code ${exitCode}: ${errText}`)
  }

  const rawJson = new TextDecoder().decode(stdoutBytes).trim()
  const parsed = JSON.parse(rawJson)
  return { rawJson, parsed }
}

const canonicalizeJson = (value: any): any => {
  if (Array.isArray(value)) return value.map(canonicalizeJson)
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value).sort().map((key) => [key, canonicalizeJson(value[key])])
    )
  }
  return value
}

export const schemasSemanticallyEqual = (left: unknown, right: unknown): boolean => {
  return JSON.stringify(canonicalizeJson(left)) === JSON.stringify(canonicalizeJson(right))
}

export const generateProtocolSource = (protocol: number, schemaVersion: number): string => {
  return `// Generated by scripts/sync-herdr-schema.ts - do not edit directly
export const HERDR_TRACKED_PROTOCOL = ${protocol}
export const HERDR_TRACKED_SCHEMA_VERSION = ${schemaVersion}
`
}

const main = async () => {
  const isCheck = process.argv.includes('--check')
  const { rawJson, parsed } = await fetchInstalledSchema()

  const protocol = parsed.protocol
  const schemaVersion = parsed.schema_version

  if (typeof protocol !== 'number' || typeof schemaVersion !== 'number') {
    console.error('Error: schema output missing valid protocol or schema_version fields.')
    process.exit(1)
  }

  if (protocol !== 22 || schemaVersion !== 1) {
    console.error(`Error: unexpected installed protocol=${protocol}, schema_version=${schemaVersion}. Expected protocol=22, schema_version=1.`)
    process.exit(1)
  }

  if (isCheck) {
    if (!existsSync(SCHEMA_FILE) || !existsSync(PROTOCOL_FILE)) {
      console.error(`Error: generated files missing in ${GENERATED_DIR}. Run "bun run schema:sync" first.`)
      process.exit(1)
    }

    const existingSchemaJson = readFileSync(SCHEMA_FILE, 'utf8').trim()
    const existingProtocolSource = readFileSync(PROTOCOL_FILE, 'utf8')

    // Compare parsed values so formatting and object key order are harmless, while every schema field is checked.
    const existingParsed = JSON.parse(existingSchemaJson)
    if (!schemasSemanticallyEqual(existingParsed, parsed)) {
      console.error('Error: server/generated/herdr-schema.json is semantically different from the installed Herdr schema.')
      process.exit(1)
    }

    const expectedProtocolSource = generateProtocolSource(protocol, schemaVersion)
    if (existingProtocolSource.trim() !== expectedProtocolSource.trim()) {
      console.error('Error: server/generated/protocol.ts is out of sync with installed Herdr metadata.')
      process.exit(1)
    }

    console.log(`[schema:check] OK: installed Herdr protocol=${protocol}, schema_version=${schemaVersion} matches tracked repository files.`)
    process.exit(0)
  }

  // Sync mode: write files
  mkdirSync(GENERATED_DIR, { recursive: true })
  // Pretty-print JSON
  writeFileSync(SCHEMA_FILE, JSON.stringify(parsed, null, 2) + '\n', 'utf8')
  writeFileSync(PROTOCOL_FILE, generateProtocolSource(protocol, schemaVersion), 'utf8')

  console.log(`[schema:sync] Wrote installed schema (protocol=${protocol}, schema_version=${schemaVersion}) to ${SCHEMA_FILE} and ${PROTOCOL_FILE}`)
}

if (import.meta.main) {
  main().catch((err) => {
    console.error(`[schema] Failed: ${err instanceof Error ? err.message : String(err)}`)
    process.exit(1)
  })
}
